fruits=['orange','apple','pear','banana','apple','kiwi']
print(fruits.count('orange'))
fruits.sort()
print(fruits)
numbers=[3,5,1,9,10]
numbers.sort()
print(sorted(numbers))
numbers.clear()
numbers_copy=numbers.copy()
print(numbers_copy)
